easy_admin:
    site_name: 'ESO-Raidplanner'
    user:
        avatar_property_path: 'fullAvatarUrl'
    formats:
        date: 'd-m-Y'
        time: 'H:i:s'
        datetime: 'd-m-y H:i:s'

    entities:
        # List the entity class name you want to manage
        ArmorSet:
            class: App\Entity\ArmorSet
            label: Armor Sets
        CharacterPreset:
            class: App\Entity\CharacterPreset
            label: Character Presets
        Comment:
            class: App\Entity\Comment
            label: Comments
        DiscordChannel:
            class: App\Entity\DiscordChannel
            label: Discord Channels
        DiscordGuild:
            class: App\Entity\DiscordGuild
            label: Discord Guilds
            list:
                sort: ['name', 'ASC']
                dql_filter: 'entity.active = 1'
                fields:
                    - { property: 'fullIconUrl', type: 'image' }
                    - { property: 'name' }
                    - { property: 'id' }
                    - { property: 'owner' }
                    - { property: 'members' }
                    - { property: 'active' }
                    - { property: 'botActive' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'id' }
                    - { property: 'owner' }
                    - { property: 'active' }
                    - { property: 'botActive' }
        Event:
            class: App\Entity\Event
            label: Events
        EventAttendee:
            class: App\Entity\EventAttendee
            label: Event Attendees
        RecurringEvent:
            class: App\Entity\RecurringEvent
            label: Recurring Events
        Reminder:
            class: App\Entity\Reminder
            label: Reminders
        User:
            class: App\Entity\User
            label: Users
            list:
                sort: ['username', 'ASC']
                fields:
                    - { property: 'id' }
                    - { property: 'fullAvatarUrl', type: 'image' }
                    - { property: 'username' }
                    - { property: 'discordDiscriminator' }
                    - { property: 'discordId' }
                    - { property: 'clock' }
                    - { property: 'timezone' }
            form:
                fields:
                    - { property: 'username' }
                    - { property: 'discordDiscriminator' }
                    - { property: 'discordId' }
                    - { property: 'clock' }
                    - { property: 'timezone' }
                    - { property: 'darkmode' }
                    - { property: 'firstDayOfWeek' }
                    - { property: 'patreonMembership' }

    design:
        assets:
            favicon: '/build/images/favicon/favicon-96x96.png'
        menu:
            - { label: Application }
            - {label: Armor Sets, icon: shield, entity: ArmorSet}
            - {label: Character Presets, icon: users, entity: CharacterPreset}
            - {label: Comments, icon: comment, entity: Comment}
            - {label: Events, icon: calendar, entity: Event}
            - {label: Event Attendees, icon: user-clock, entity: EventAttendee}
            - {label: Recurring Events, icon: sync, entity: RecurringEvent}
            - {label: Reminders, icon: exclamation, entity: Reminder}
            - { label: Discord}
            - {label: Discord Channels, icon: bullhorn, entity: DiscordChannel}
            - {label: Discord Guilds, icon: university, entity: DiscordGuild}
            - {label: Users, icon: user, entity: User}