name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - '7.3'
#          - '7.4'

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov

      - name: php --version
        run: php --version

      - name: composer --version
        run: composer --version

      - name: (COMPOSER) Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: (CGL) PHP
        run: php bin/php-cs-fixer fix --config build/.php_cs.dist --dry-run

      - name: Yarn install
        run: yarn install
  
      - name: Yarn build
        run: yarn build
