name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - '7.3'

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov

      - name: php --version
        run: php --version

      - name: composer --version
        run: composer --version
      
      - name: Copy .env
        run: cp .env.example .env

      - name: (COMPOSER) Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: (CGL) PHP
        run: php bin/php-cs-fixer fix --config build/.php_cs -v --dry-run --diff

      - name: Yarn install
        run: yarn install --silent --non-interactive
  
      - name: Yarn build
        run: yarn build

      - name: Trigger deployment
        if: github.ref == 'refs/heads/master'
        run: wget -q ${{ secrets.DEPLOYMENT_TRIGGER_URL }}
